### ISSUE TITLE
marshal

### ISSUE THREAD

**Issue by 89z** [dannyhann/protobuf_decoder#2]
Does this package have an support for encoding? Or only decoding

**Comment by dannyhann** [comment]
hi, @89z 
I'm sorry for the late response.

The `protobuf_decoder` only decodes.
`protobuf` encodes with a proto file, and typically decoded based on a proto files

When you don't have proto files, and need to parse protobuf binary data.
`protobuf_decoder` will be usefull

The `protobuf_decoder` is a library where you can analyze content without a proto file.
